#!/usr/bin/env python3
"""Merge yt-dlp playlist dumps + curated content.json into the app's data.js."""
import json
import pathlib
import sys

SCRATCH = pathlib.Path(__file__).parent
OUT = SCRATCH.parent / "data.js"

# Playlist display order: mental game first (per Jamie), then the
# purpose-built series, core library, how-tos, misc, breakdowns.
PLAYLIST_ORDER = [
    ("PL-eXJm5v4ABZn0SE1IVRKRXFqcRDO7jLU", "Mental Skills",
     "The inner game: confidence, slumps, routines, and lessons from 9 years in the minors."),
    ("PL-eXJm5v4ABYVTI9m3Y3CPPuqSEg4L5jd", "The Setup",
     "An 11-part, purpose-built series. Watch strictly in order — each part builds on the last."),
    ("PL-eXJm5v4ABY4pFs2-dmzgQzx3v7t_Gmn", "Backspin & Hitting",
     "The core library: why backspin is the #1 priority and how to build a swing that creates it."),
    ("PL-eXJm5v4ABZ2F8RbtkqLIUg4MDrl8ZJk", "How to Videos",
     "Practical fixes and how-tos — pull these in as specific problems show up in your swing."),
    ("PL-eXJm5v4ABaEObU-UkQFu7-bIgTVvDnG", "Unfinished Player Development",
     "Odds and ends from the Unfinished PD program."),
    ("PL-eXJm5v4ABbxO8W9E2rroOvyvFjii2Cw", "Swing Breakdowns",
     "Elite swings under the microscope — watch these last and test your eye."),
]

# Videos whose owner disabled embedded playback (YouTube error 150/101).
# Found by probing all 67 with the IFrame API on 2026-07-17; the app shows a
# direct YouTube link for these instead of an inline player.
NO_EMBED = {"kiUMz_HTyFw"}

PHASE_NAMES = {
    0: "Orientation",
    1: "The Setup",
    2: "Backspin & Swing Fundamentals",
    3: "Diagnosing & Fixing Swing Flaws",
    4: "Translating Practice Into Games",
    5: "Mental Game & Long-Term Development",
    6: "Applied & Advanced Study",
}

content = json.loads((SCRATCH / "content.json").read_text())
quiz = json.loads((SCRATCH / "quiz.json").read_text())

# Flatten curated content into id -> record, with global curriculum sequence.
curated = {}
seq = 0
for phase in content["phases"]:
    for v in phase["videos"]:
        seq += 1
        curated[v["id"]] = {
            "phase": phase["n"],
            "seq": seq,
            "overview": v["overview"],
            "takeaways": v["takeaways"],
        }

videos = {}   # id -> merged record
playlists = []
for pl_id, pl_name, pl_blurb in PLAYLIST_ORDER:
    d = json.loads((SCRATCH / f"pl_{pl_id}.json").read_text())
    seen = set()
    vid_ids = []
    for e in d["entries"]:
        vid = e["id"]
        if e.get("title") is None:
            print(f"  note: skipping unavailable video {vid} in '{pl_name}'")
            continue
        if vid in seen:
            continue  # duplicate within the same playlist
        seen.add(vid)
        vid_ids.append(vid)
        if vid not in videos:
            videos[vid] = {
                "id": vid,
                "title": e["title"],
                "duration": int(e["duration"] or 0),
            }
            if vid in NO_EMBED:
                videos[vid]["noEmbed"] = True
    playlists.append({"id": pl_id, "name": pl_name, "blurb": pl_blurb, "videos": vid_ids})

# Validate: curated and scraped sets must match exactly.
scraped_ids = set(videos)
curated_ids = set(curated)
missing = scraped_ids - curated_ids
extra = curated_ids - scraped_ids
if missing or extra:
    if missing:
        print("MISSING content for:", *(f"  {i} {videos[i]['title']}" for i in missing), sep="\n")
    if extra:
        print("EXTRA content ids:", *extra, sep="\n  ")
    sys.exit(1)

# Validate quiz coverage and shape: every video gets exactly 3 questions,
# each with 4 choices, a valid answer index, an explanation, and a review
# timestamp inside the video.
quiz_missing = scraped_ids - set(quiz)
quiz_extra = set(quiz) - scraped_ids
if quiz_missing or quiz_extra:
    if quiz_missing:
        print("MISSING quiz for:", *(f"  {i} {videos[i]['title']}" for i in quiz_missing), sep="\n")
    if quiz_extra:
        print("EXTRA quiz ids:", *quiz_extra, sep="\n  ")
    sys.exit(1)
for vid, questions in quiz.items():
    dur = videos[vid]["duration"]
    if len(questions) != 3:
        sys.exit(f"quiz for {vid} has {len(questions)} questions, want 3")
    for q in questions:
        if (len(q["choices"]) != 4 or not 0 <= q["answer"] <= 3
                or not q["explain"] or not 0 <= q["t"] < dur):
            sys.exit(f"malformed quiz question in {vid}: {q['q']!r}")

for vid, rec in videos.items():
    rec.update(curated[vid])
    rec["quiz"] = quiz[vid]

out = {
    "channel": "Anderson Miller — Unfinished Player Development",
    "channelUrl": "https://www.youtube.com/@andersonLmiller",
    "phaseNames": PHASE_NAMES,
    "playlists": playlists,
    "videos": videos,
}
OUT.write_text(
    "// Generated by scripts/gen_data.py — do not edit by hand.\n"
    "const DATA = " + json.dumps(out, indent=2, ensure_ascii=False) + ";\n"
)
n_vids = len(videos)
total_min = sum(v["duration"] for v in videos.values()) / 60
print(f"OK: {len(playlists)} playlists, {n_vids} unique videos, {total_min:.0f} min total -> {OUT}")
