#!/usr/bin/env python3
"""Merge yt-dlp playlist dumps + curated content.json into the app's data.js."""
import json
import pathlib
import sys

SCRATCH = pathlib.Path(__file__).parent
OUT = SCRATCH.parent / "data.js"

# Playlist display order: purpose-built series first, then core library,
# how-tos, mental, misc, breakdowns.
PLAYLIST_ORDER = [
    ("PL-eXJm5v4ABYVTI9m3Y3CPPuqSEg4L5jd", "The Setup",
     "An 11-part, purpose-built series. Watch strictly in order — each part builds on the last."),
    ("PL-eXJm5v4ABY4pFs2-dmzgQzx3v7t_Gmn", "Backspin & Hitting",
     "The core library: why backspin is the #1 priority and how to build a swing that creates it."),
    ("PL-eXJm5v4ABZ2F8RbtkqLIUg4MDrl8ZJk", "How to Videos",
     "Practical fixes and how-tos — pull these in as specific problems show up in your swing."),
    ("PL-eXJm5v4ABZn0SE1IVRKRXFqcRDO7jLU", "Mental Skills",
     "The inner game: confidence, slumps, routines, and lessons from 9 years in the minors."),
    ("PL-eXJm5v4ABaEObU-UkQFu7-bIgTVvDnG", "Unfinished Player Development",
     "Odds and ends from the Unfinished PD program."),
    ("PL-eXJm5v4ABbxO8W9E2rroOvyvFjii2Cw", "Swing Breakdowns",
     "Elite swings under the microscope — watch these last and test your eye."),
]

PHASE_NAMES = {
    0: "Orientation",
    1: "The Setup",
    2: "Backspin & Swing Fundamentals",
    3: "Diagnosing & Fixing Swing Flaws",
    4: "Translating Practice Into Games",
    5: "Mental Game & Long-Term Development",
    6: "Applied & Advanced Study",
}

content = json.loads((SCRATCH / "content.json").read_text())

# Flatten curated content into id -> record, with global curriculum sequence.
curated = {}
seq = 0
for phase in content["phases"]:
    for v in phase["videos"]:
        seq += 1
        curated[v["id"]] = {
            "phase": phase["n"],
            "seq": seq,
            "overview": v["overview"],
            "takeaways": v["takeaways"],
        }

videos = {}   # id -> merged record
playlists = []
for pl_id, pl_name, pl_blurb in PLAYLIST_ORDER:
    d = json.loads((SCRATCH / f"pl_{pl_id}.json").read_text())
    seen = set()
    vid_ids = []
    for e in d["entries"]:
        vid = e["id"]
        if e.get("title") is None:
            print(f"  note: skipping unavailable video {vid} in '{pl_name}'")
            continue
        if vid in seen:
            continue  # duplicate within the same playlist
        seen.add(vid)
        vid_ids.append(vid)
        if vid not in videos:
            videos[vid] = {
                "id": vid,
                "title": e["title"],
                "duration": int(e["duration"] or 0),
            }
    playlists.append({"id": pl_id, "name": pl_name, "blurb": pl_blurb, "videos": vid_ids})

# Validate: curated and scraped sets must match exactly.
scraped_ids = set(videos)
curated_ids = set(curated)
missing = scraped_ids - curated_ids
extra = curated_ids - scraped_ids
if missing or extra:
    if missing:
        print("MISSING content for:", *(f"  {i} {videos[i]['title']}" for i in missing), sep="\n")
    if extra:
        print("EXTRA content ids:", *extra, sep="\n  ")
    sys.exit(1)

for vid, rec in videos.items():
    rec.update(curated[vid])

out = {
    "channel": "Anderson Miller — Unfinished Player Development",
    "channelUrl": "https://www.youtube.com/@andersonLmiller",
    "phaseNames": PHASE_NAMES,
    "playlists": playlists,
    "videos": videos,
}
OUT.write_text(
    "// Generated by scripts/gen_data.py — do not edit by hand.\n"
    "const DATA = " + json.dumps(out, indent=2, ensure_ascii=False) + ";\n"
)
n_vids = len(videos)
total_min = sum(v["duration"] for v in videos.values()) / 60
print(f"OK: {len(playlists)} playlists, {n_vids} unique videos, {total_min:.0f} min total -> {OUT}")
